
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwtSecret: javainusesecretkeyjavainusesecretkeyjavainusesecretkeyjavainusesecretkey
jwtExpirationMs: 86400000  # 1day
jwtRefreshExpirationSecond: 25920000  # 1month

spring:
  application:
    name: auth-service
  datasource:
    url:  jdbc:mysql://localhost:3308/spring_blog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8082


