version: "3.9"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_comment
    expose:
      - "3312"
    ports:
      - "3312:3306"