version: "3.9"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_post
    expose:
      - "3309"
    ports:
      - "3309:3306"