version: "3.9"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_blog
    expose:
      - "3308"
    ports:
      - "3308:3306"