eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: '0'
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: '8761'